os:
  - linux
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
script:
  - npm run vuln-scan
  - npm test
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
